In [7]:
import pandas as pd
import torch
import numpy as np

In [13]:
def softmax(a):
  
  a=a/np.linalg.norm(a,axis=0,keepdims=True)

  if len(a.shape)>1:
    max_matrix=np.max(a,axis=0) #compare all the rows for each column and takes the bigger value for each column make a single vector
    stable = a-max_matrix
    e=np.exp(stable)
    A= e/np.sum(e,axis=0)
  else : #If there is only one matrix
    max_matrix=np.max(a) #Take the max_value from the single vector
    stable = a-max_matrix
    e=np.exp(stable)
    A= e/np.sum(e)

  return (torch.tensor(A))

a=softmax(np.array([1,2,3])) 
print(a)

tensor([0.2492, 0.3255, 0.4253], dtype=torch.float64)


In [ ]:

def wordvec(sentences,tokens,n_dim):
  no_of_tokens=len(tokens)
  one_hot=np.eye(no_of_tokens)



In [ ]:
a=torch.arange(5,dtype=torch.float32)


tensor([0., 1., 2., 3., 4.])


In [11]:
a=np.array([[1,2,3]])
print(a)
b=np.linalg.norm(a,axis=1,keepdims=True)
print(b)

[[1 2 3]]
[[3.74165739]]


In [17]:
a=np.array(['sid','hai'])
print(a)
b=torch.Tensor(a)
print(b)

['sid' 'hai']


TypeError: can't convert np.ndarray of type numpy.str_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint64, uint32, uint16, uint8, and bool.